import type { Metadata } from 'next';
import './globals.css';

// Constants
import { abel } from '@/constants/fonts';

// Layouts
import { Header, Footer } from '@/ui/layouts';

export const metadata: Metadata = {
  title: 'Smart web',
  description: 'Generated by Smart web'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={abel.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
